export const categories = [
    {
        id: 1,
        title: 'Criptomoedas',
        img: 'https://images.pexels.com/photos/8369677/pexels-photo-8369677.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
        id: 2,
        title: 'NFTs',
        img: 'https://images.pexels.com/photos/13528110/pexels-photo-13528110.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
        id: 3,
        title: 'Utility Tokens',
        img: 'https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
];

export const popularProducts = [
    {
        id: 1,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-gmt-color.svg',
        title: 'Stepn (GMT)',
        segment: 'Utility Token',
        description: '+3.07% nas últimas 24 horas',
        price: 'Cotação R$ 2,43',
    },
    {
        id: 2,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-rose-color.svg',
        title: 'Oasis Network (ROSE)',
        segment: 'Utility Token',
        description: '-6.15% nas últimas 24 horas',
        price: 'Cotação R$ 0,26',
    },
    {
        id: 3,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-agix-color.svg',
        title: 'SingularityNET (AGIX)',
        segment: 'DeFi',
        description: '+7.76% nas últimas 24 horas',
        price: 'Cotação R$ 0,249',
    },
    {
        id: 4,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-ape-color.svg',
        title: 'ApeCoin (APE)',
        segment: 'Utility Tokens',
        description: '-5.08% nas últimas 24 horas',
        price: 'Cotação R$ 18,78',
    },
    {
        id: 5,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-btc-color.svg',
        title: 'Bitcoin (BTC)',
        segment: 'Criptomoeda',
        description: '-4,86% nas últimas 24 horas',
        price: 'Cotação R$ 88.431,74',
    },
    {
        id: 6,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-ada-color.svg',
        title: 'Cardano (ADA)',
        segment: 'Criptomoeda',
        description: '+0,11% nas últimas 24 horas',
        price: 'Cotação R$ 1,89',
    },
    {
        id: 7,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-dot-color.svg',
        title: 'Polkadot (DOT)',
        segment: 'Criptomoeda',
        description: '-6,86% nas últimas 24 horas',
        price: 'Cotação R$ 30,64',
    },
    {
        id: 8,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-aave-color.svg',
        title: 'Aave (AAVE)',
        segment: 'DeFi',
        description: '-3,30% nas últimas 24 horas',
        price: 'Cotação R$ 1,95',
    },
    {
        id: 9,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-stg-color.svg',
        title: 'Stargate Finance (STG)',
        segment: 'DeFi',
        description: '-8.09% nas últimas 24 horas',
        price: 'Cotação R$ 2,16',
    },
    {
        id: 10,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-ltc-color.svg',
        title: 'Litecoin (LTC)',
        segment: 'Criptomoeda',
        description: '+2,22% nas últimas 24 horas',
        price: 'Cotação R$ 304,98',
    },
    {
        id: 11,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-audio-color.svg',
        title: 'Audius (AUDIO)',
        segment: 'Utility Tokens',
        description: '-3.46% nas últimas 24 horas',
        price: 'Cotação R$ 0,88',
    },
    {
        id: 12,
        icon: 'https://static.mercadobitcoin.com.br/web/img/icons/assets/ico-asset-alcx-color.svg',
        title: 'Alchemix (ALCX)',
        segment: 'DeFi',
        description: '+3.53% nas últimas 24 horas',
        price: 'Cotação R$ 102,94',
    },
];